"""Fix expense field typo

Revision ID: 35147e57a400
Revises: af840892682a
Create Date: 2025-01-03 18:19:18.656832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35147e57a400'
down_revision = 'af840892682a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expense', sa.String(length=64), nullable=False))
        batch_op.drop_column('expence')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expence', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
        batch_op.drop_column('expense')

    # ### end Alembic commands ###
