"""Allow NULL in category_id

Revision ID: 6cf237032d08
Revises: 35147e57a400
Create Date: 2025-01-03 18:34:43.775688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cf237032d08'
down_revision = '35147e57a400'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('record', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.alter_column('category_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.drop_constraint('record_category_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('record_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'category', ['category_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('record', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('record_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key('record_category_id_fkey', 'category', ['category_id'], ['id'])
        batch_op.alter_column('category_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               nullable=False)

    # ### end Alembic commands ###
