"""Change endpoints and model

Revision ID: af840892682a
Revises: 2093ad45b470
Create Date: 2025-01-03 18:10:55.733260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af840892682a'
down_revision = '2093ad45b470'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('record', schema=None) as batch_op:
        batch_op.alter_column('expence',
               existing_type=sa.REAL(),
               type_=sa.String(length=64),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('record', schema=None) as batch_op:
        batch_op.alter_column('expence',
               existing_type=sa.String(length=64),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
